services:
  neo4j:
    image: neo4j:5-community
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_server_memory_heap_max__size: 24G
      NEO4J_server_memory_heap_initial__size: 8G
      NEO4J_server_memory_pagecache_size: 4G
      NEO4J_dbms_memory_transaction_total_max: 16G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./data/raw/202606:/var/lib/neo4j/import/companies

volumes:
  neo4j_data:
  neo4j_logs:
